### ISSUE TITLE
Error thrown while minecraft facet detection is happening

### ISSUE THREAD

**Issue by zml2008** [Earthcomputer/MinecraftDev#5]
Hi there,

The fabric support in this plugin seems to be having some issues detecting my project -- a quick glance suggests this is something with assuming every classes root in the project is a jar, when some of them are not. All the projects I'm working with existed before installing the MinecraftDev plugin.

* Minecraft Development for IntelliJ plugin version: 2019.3-1.3.2-earth.23
* IntelliJ version: 2019.3.4
* Operating System (this has come up enough times to be important): Windows 10
* Target platforms: Occurred on Fabric - in [PEXPlugins/PermissionsEx](https://github.com/PEXPlugins/PermissionsEx), but i've also seen the issue appear in Forge projects like Sponge

## Stacktrace

```java
java.io.FileNotFoundException: C:\Users\Zach\dev\PermissionsEx\buildSrc\build\pluginUnderTestMetadata (Access is denied)
	at java.base/java.io.RandomAccessFile.open0(Native Method)
	at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:345)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:214)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1271)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1237)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:844)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:247)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:346)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:317)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:283)
	at com.demonwav.mcdev.platform.fabric.framework.FabricPresentationProvider.detect(FabricPresentationProvider.kt:26)
	at com.demonwav.mcdev.platform.fabric.framework.FabricPresentationProvider.detect(FabricPresentationProvider.kt:20)
	at com.intellij.openapi.roots.impl.libraries.LibraryDetectionManagerImpl.computeKinds(LibraryDetectionManagerImpl.java:77)
	at com.intellij.openapi.roots.impl.libraries.LibraryDetectionManagerImpl.getOrComputeKinds(LibraryDetectionManagerImpl.java:66)
	at com.intellij.openapi.roots.impl.libraries.LibraryDetectionManagerImpl.processProperties(LibraryDetectionManagerImpl.java:39)
	at com.intellij.openapi.roots.ui.configuration.libraries.impl.LibraryPresentationManagerImpl.isLibraryOfKind(LibraryPresentationManagerImpl.java:138)
	at com.demonwav.mcdev.facet.MinecraftModuleRootListener$autoDetectTypes$1.invoke(MinecraftModuleRootListener.kt:102)
	at com.demonwav.mcdev.facet.MinecraftModuleRootListener$autoDetectTypes$1.process(MinecraftModuleRootListener.kt:27)
	at com.intellij.openapi.roots.impl.OrderEnumeratorBase.lambda$forEachLibrary$1(OrderEnumeratorBase.java:362)
	at com.intellij.openapi.roots.impl.OrderEnumeratorBase.processEntries(OrderEnumeratorBase.java:325)
	at com.intellij.openapi.roots.impl.ModuleOrderEnumerator.forEach(ModuleOrderEnumerator.java:48)
	at com.intellij.openapi.roots.impl.OrderEnumeratorBase.forEachLibrary(OrderEnumeratorBase.java:358)
	at com.intellij.openapi.roots.impl.ModuleOrderEnumerator.forEachLibrary(ModuleOrderEnumerator.java:33)
	at com.demonwav.mcdev.facet.MinecraftModuleRootListener.autoDetectTypes(MinecraftModuleRootListener.kt:100)
	at com.demonwav.mcdev.facet.MinecraftModuleRootListener.checkNoFacet(MinecraftModuleRootListener.kt:52)
	at com.demonwav.mcdev.facet.MinecraftModuleRootListener.doCheck(MinecraftModuleRootListener.kt:44)
	at com.demonwav.mcdev.facet.MinecraftFacetDetector$projectOpened$1.run(MinecraftFacetDetector.kt:25)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:454)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivities(StartupManagerImpl.java:404)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$runStartupActivities$0(StartupManagerImpl.java:141)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:796)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runStartupActivities(StartupManagerImpl.java:131)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.doLoadProject(ProjectManagerImpl.java:456)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.loadProjectUnderProgress(ProjectManagerImpl.java:443)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.openProject(ProjectManagerImpl.java:419)
	at com.intellij.platform.PlatformProjectOpenProcessor.lambda$openExistingProject$0(PlatformProjectOpenProcessor.java:268)
	at com.intellij.platform.ProjectUiFrameAllocator$run$1$1.run(ProjectFrameAllocator.kt:77)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:247)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:888)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$4(ApplicationImpl.java:441)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.util.ConcurrencyUtil.lambda$underThreadNameRunnable$3(ConcurrencyUtil.java:209)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by Earthcomputer** [comment]
Thanks for your report! This issue will be addressed in the upstream version: https://github.com/minecraft-dev/MinecraftDev/pull/733
